# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TableViewBuddyExample' do

end

target 'TableViewBuddyExampleTests', :exclusive => true do
  pod 'KIF', '~> 3.0', :configurations => ['Debug']
  pod 'KIF/IdentifierTests', '~> 3.0', :configurations => ['Debug']
  pod 'Expecta', '~> 0.2.4'
end
