source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TableViewBuddy_Example', :exclusive => true do
  pod 'TableViewBuddy', :path => '../'
end

target 'TableViewBuddy_Tests', :exclusive => true do
  pod 'TableViewBuddy', :path => '../'

  pod 'KIF', '~> 3.0'
  pod 'KIF/IdentifierTests', '~> 3.0'
  pod 'Expecta'
end
